name: "FibBot"
description: "A GitHub Action that scans PRs for numbers, computes their Fibonacci values, and comments on the PR."
author: "Your Name or GitHub Username"

inputs:
  enable_fib:
    description: "Enable Fibonacci calculation (true/false)"
    required: false
    default: "true"
  max_threshold:
    description: "Maximum number allowed for Fibonacci calculation"
    required: false
    default: "100"

runs:
  using: "docker"
  image: "Dockerfile"  

branding:
  icon: "zap"
  color: "blue"
