name: "FibBot"
description: "A GitHub Action that calculates Fibonacci numbers"
inputs:
  github_token:
    description: "GitHub Token for authentication"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
