inputs: 
  enable_fibb:
    description: 'Enable Fibonacci calculation (true / false)'
    required: 'false'
    default: 'true'
  max_threshold:
    description: ' Maximum number for Fibonacci calculation'
    required: 'false'
    default: '100'
