name: fibbot action
description: A GitHub Action that extracts numbers from PRs and posts Fibonacci results.
author: "tegha-romeo"

inputs:
  github_token:
    description: "GitHub Token for authentication"
    required: true
  pr_number:
    description: "Pull Request number"
    required: true

runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: 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
    PR_NUMBER: ${{ inputs.pr_number }}
