name: "FibBot"
description: "A GitHub Action that scans PRs for numbers, computes their Fibonacci values, and comments on the PR."
author: "Your Name or GitHub Username"

inputs:
  enable_fib:
    description: "Enable Fibonacci calculation (true/false)"
    required: false
    default: "true"
  max_threshold:
    description: "Maximum number allowed for Fibonacci calculation"
    required: false
    default: "100"

runs:
  using: "docker"
<<<<<<< HEAD
  image: "Dockerfile"  
=======
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 685236761059b3de6248d4be0fd7ea27aaa1eaa5

branding:
  icon: "zap"
  color: "blue"
