name: Test FibBot
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
<<<<<<< HEAD

      - name: Run FibBot Action
        uses: ./
        with:
          enable_fib: "true"
          max_threshold: "100"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
=======
      
      - name: Run FibBot Action
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}  # Use the new secret name
>>>>>>> 685236761059b3de6248d4be0fd7ea27aaa1eaa5
