name: Test FibBot
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run FibBot Action
        uses: ./
        with:
          enable_fib: "true"
          max_threshold: "100"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
